### ISSUE TITLE
运行 $ npm start 命令后无反应

### ISSUE THREAD

**Issue by pdog18** [heimashi/easy_mock_api#4]
>$ npm start
> easy_mock_api@1.0.0 start H:\node.js\easy_mock_api
> node app.js
>app listening at post 3000
>{}

一直处于等待状态，localhost也不能访问 ,但是访问`http://127.0.0.1:3000/`时是可以的。

新手不太懂，这个命令执行后命令行就要一直挂起吧？不好意思

**Comment by heimashi** [comment]
对的，项目默认是在3000端口运行，你可以访问http://localhost:3000地址，或者改成80端口后访问http://localhost

**Comment by bailangsyc** [comment]
@heimashi  你的qq号是多少 ，可以加一下你吗
